
import { TeachingPlan } from './types';

export const SENAI_BLUE = "#005DAA";
export const SENAI_RED = "#E30613";

// --- CRONOGRAMA LIDT ---
export const LIDT_SCHEDULE = [
  { id: 'l1', date: '26/01/2026', hours: 2, capacities: 'Todas as capacidades da SA', knowledge: '1.1. Definição de Desenho Técnico', strategy: '• Exposição dialogada; • Apresentação da UC, do MSEP e da Situação de Aprendizagem "Decifrando o Projeto"; • Dinâmica de Grupo: Formação das equipes e discussão inicial sobre a importância do desenho técnico no mundo do trabalho.', resources: 'Sala de aula, projetor, computador, Plano de Ensino, material da SA.' },
  { id: 'l2', date: '02/02/2026', hours: 2, capacities: 'Interpretar desenhos técnicos de peças.', knowledge: '1.2. Normas técnicas; 1.3. Formatos de folha; 1.4. Linhas.', strategy: '• Exposição dialogada: Apresentação das normas ABNT, foramatos de papel e tipos de linhas. • Atividade prática: Análise de desenhos técnicos para identificação dos tipos de linhas e suas aplicações.', resources: 'Sala de aula, projetor, exemplos de desenhos técnicos, apostila.' },
  { id: 'l3', date: '09/02/2026', hours: 2, capacities: 'Interpretar desenhos técnicos de peças.', knowledge: '1.5. Escalas; 1.6. Figuras e sólidos geométricos.', strategy: '• Exposição dialogada e Demonstração: Explicação sobre escalas (natural, redução, ampliação). • Apresentação de figuras e sólidos geométricos.', resources: 'Projetor, modelos de sólidos geométricos, desenhos com diferentes escalas.' },
  { id: 'l4', date: '16/02/2026', hours: 2, capacities: 'Elaborar croquis de peças.', knowledge: '2.1. Perspectiva (isométrica, vistas)...', strategy: '• Atividade prática: Introdução à perspectiva isométrica. Exercícios de esboço à mão livre de sólidos geométricos simples em perspectiva.', resources: 'Sala de aula, papel, lps, borracha, modelos de sólidos.' },
  { id: 'l5', date: '23/02/2026', hours: 2, capacities: 'Elaborar croquis de peças.', knowledge: '2.2. Projeção ortogonal (vistas, supressão de vistas).', strategy: '• Atividade prática: Desenho das 3 vistas principais (frontal, superior, lateral) a partir de modelos sólidos simples. Discussão sobre supressão de vistas.', resources: 'Sala de aula, papel, lps, borracha, modelos de peças simples.' },
  { id: 'l6', date: '02/03/2026', hours: 2, capacities: 'Elaborar croquis de peças.', knowledge: '2.5. Cotagem (vistas únicas, face de referência, eixo de simetria).', strategy: '• Exposição dialogada e Prática: Apresentação das regras de cotagem. Exercícios de cotagem de vistas ortogonais.', resources: 'Projetor, exemplos de desenhos cotados, exercícios impressos.' },
  { id: 'l7', date: '09/03/2026', hours: 2, capacities: 'Interpretar desenhos técnicos de peças.', knowledge: '3.1. Cortes... 3.2. Meio corte.', strategy: '• Exposição dialogada e Demonstração: Explicação da necessidade e representação de cortes. Análise de desenhos com corte total e meio corte.', resources: 'Projetor, desenhos técnicos com cortes, pecas seccionadas (se disponível).' },
  { id: 'l8', date: '16/03/2026', hours: 2, capacities: 'Interpretar desenhos técnicos de peças.', knowledge: '3.3 a 3.7. Outros tipos de corte (composto, parcial, seção, omissão, encurtamento).', strategy: '• Estudo de caso: As equipes analisam desenhos complexos e identificam os diferentes tipos de cortes e seções, discutindo sua aplicação.', resources: 'Projetor, conjunto de desenhos técnicos variados.' },
  { id: 'l9', date: '23/03/2026', hours: 2, capacities: 'Elaborar croquis de peças.', knowledge: '4. Vistas especiais (auxiliares, rotação de elemento).', strategy: '• Atividade prática: Exercícios de desenho de vistas auxiliares para representação de faces inclinadas.', resources: 'Sala de aula, papel, instrumentos de desenho, modelos de peças com faces inclinadas.' },
  { id: 'l10', date: '30/03/2026', hours: 2, capacities: 'Interpretar desenho técnico de montagem.', knowledge: '5. Desenho de conjuntos (representação, elementos, vista explodida).', strategy: '• Exposição dialogada: Apresentação da estrutura de um desenho de conjunto, vista explodida e elementos padronizados.', resources: 'Projetor, exemplo de desenho de conjunto comlplexo (ex: morsa).' },
  { id: 'l11', date: '06/04/2026', hours: 2, capacities: 'Interpretar desenho técnico de montagem.', knowledge: '5.3. Lista de materiais; 5.4. Balões de identificação.', strategy: '• Atividade em equipe: Análise do desenho de "Subconjunto do Acoplamento AC-102". As equipes devem correlacionar a lista de materiais com os balões na vista explodida.', resources: 'Cópia do desenho da SA para cada equipe, projetor.' },
  { id: 'l12', date: '13/04/2026', hours: 2, capacities: 'Interpretar tolerância dimensional.', knowledge: '6.1. Tolerância dimensional (campos, sistema ISO).', strategy: '• Exposição dialogada: Introdução aos conceitos de tolerância, afastamentos e sistema de ajuste ISO (eixo-base e furo-base).', resources: 'Projetor, tabelas de tolerância ISO, exemplos de eixos e furos com ajustes.' },
  { id: 'l13', date: '27/04/2026', hours: 2, capacities: 'Interpretar tolerância geométrica.', knowledge: '6.2. Tolerância geométrica (forma, posição, orientação, batimento).', strategy: '• Exposição dialogada: Apresentação dos símbolos e significado das principais tolerâncias geométricas (retitude, planicidade, paralelismo, etc.).', resources: 'Projetor, quadro de tolerâncias geométricas, peças de exemplo.' },
  { id: 'l14', date: '04/05/2026', hours: 2, capacities: 'Interpretar acabamento superficial.', knowledge: '6.3. Acabamento superficial (rugosidade, tratamento, recartilhado, sobremetal).', strategy: '• Exposição dialogada: Explicação dos símbolos de acabamento superficial e sua relação com os processos de fabricação.', resources: 'Projetor, tabela de símbolos de rugosidade, rugosímetros (se disponível).' },
  { id: 'l15', date: '11/05/2026', hours: 2, capacities: 'Todas as capacidades da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: '• Trabalho em equipe (Oficina): Início da elaboração dos croquis detalhados e do relatório de análise crítica do desafio proposto na SA. O docente atua como mediador.', resources: 'Sala de aula/oficina, cópias do projeto da SA, papel, instrumentos de desenho.' },
  { id: 'l16', date: '18/05/2026', hours: 2, capacities: 'Todas as capacidades da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: '• Trabalho em equipe (Oficina): Continuação e refinamento dos croquis e preenchimento da ficha de análise crítica.', resources: 'Sala de aula/oficina, cópias do projeto da SA, papel, instrumentos de desenho.' },
  { id: 'l17', date: '25/05/2026', hours: 2, capacities: 'Todas as capacidades da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: '• Trabalho em equipe (Oficina): Finalização dos croquis e do dossiê técnico. Revisão final das informações.', resources: 'Sala de aula/oficina, dossiê em fase de conclusão.' },
  { id: 'l18', date: '01/06/2026', hours: 2, capacities: 'Todas as capacidades da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: '• Apresentação dos Resultados: Equipes apresentam seus Dossiês Técnicos e explicam a análise das tolerâncias.', resources: 'Sala de aula, projetor, dossiês finalizados.' },
  { id: 'l19', date: '08/06/2026', hours: 2, capacities: 'Todas as capacidades da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: '• Feedback e Avaliação: Devolutiva do docente sobre o desempenho das equipes e autoavaliação.', resources: 'Sala de aula, fichas de avaliação.' },
  { id: 'l20', date: '15/06/2026', hours: 2, capacities: 'Todas as capacidades da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: '• Encerramento da Unidade Curricular e fechamento de notas.', resources: 'Sala de aula.' }
];

// --- CRONOGRAMA CRD ---
export const CRD_SCHEDULE = [
  { id: 'c1', date: '27/01/2026', hours: 2, capacities: 'I. Identificar a importância da metrologia na indústria metalmecânica.', knowledge: '1. Metrologia (1.1 a 1.5)', strategy: 'Apresentação da Situação de Aprendizagem (SA). Exposição dialogada sobre a importância da metrologia, normas e terminologia.', resources: 'Sala de aula, projetor, computador, material da SA.' },
  { id: 'c2', date: '03/02/2026', hours: 2, capacities: 'I. Identificar a importância da metrologia na indústria metalmecânica.', knowledge: '2. Erros de medição (2.1 a 2.4)', strategy: 'Discussão em grupo sobre os tipos e fontes de erro na medição. Demonstração de erros comuns (paralaxe, força excessiva).', resources: 'Sala de aula, projetor, instrumentos de medição para demonstração.' },
  { id: 'c3', date: '10/02/2026', hours: 2, capacities: 'II. Medir peças com escala. III. Medir peças com trena.', knowledge: '3. Escala (3.1 a 3.3). 4. Trena (4.1 a 4.3)', strategy: 'Demonstração prática do uso de escalas e trenas. Exercícios práticos de medição em peças simples.', resources: 'Laboratório de Metrologia, escalas, trenas, pecas diversas.' },
  { id: 'c4', date: '24/02/2026', hours: 2, capacities: 'IV. Medir peças com paquímetro. I. Demonstrar atenção a detalhes.', knowledge: '5. Paquímetros (5.1, 5.2)', strategy: 'Exposição dialogada sobre os tipos de paquímetros e suas características. Demonstração do manuseio correto.', resources: 'Laboratório de Metrologia, projetor, diferentes tipos de paquímetros.' },
  { id: 'c5', date: '03/03/2026', hours: 2, capacities: 'IV. Medir peças com paquímetro. I. Demonstrar atenção a detalhes.', knowledge: '5. Paquímetros (5.3, 5.4, 5.5)', strategy: 'Demonstração e exercício prático de leitura no sistema métrico (0,05mm e 0,02mm).', resources: 'Laboratório de Metrologia, paquímetros, peças didcidas com medidas conhecidas.' },
  { id: 'c6', date: '10/03/2026', hours: 2, capacities: 'IV. Medir peças com paquímetro. I. Demonstrar atenção a detalhes. I. Organizar o ambiente de trabalho e as atividades.', knowledge: '5. Paquímetros (5.5)', strategy: 'Exercício prático supervisionado de medição em peças variadas, com preenchimento de relatório simples.', resources: 'Laboratório de Metrologia, paquímetros, pecas, formulário de relatório.' },
  { id: 'c7', date: '17/03/2026', hours: 2, capacities: 'V. Medir peças no sistema métrico com micrômetro. II. Zelar pelo uso de equipamentos, instrumentos, ferramentas e materiais.', knowledge: '6. Micrômetros (6.1, 6.2, 6.3)', strategy: 'Exposição sobre os tipos de micrômetros. Demonstração do manuseio, ajuste do zero e uso da catraca.', resources: 'Laboratório de Metrologia, projetor, differentes tipos de micrômetros.' },
  { id: 'c8', date: '24/03/2026', hours: 2, capacities: 'V. Medir peças no sistema métrico com micrômetro. I. Demonstrar atenção a detalhes.', knowledge: '6. Micrômetros (6.3, 6.4, 6.5)', strategy: 'Demonstração e exercício prático de leitura no sistema métrico (0,01 mm).', resources: 'Laboratório de Metrologia, micrômetros, peças didáticas.' },
  { id: 'c9', date: '31/03/2026', hours: 2, capacities: 'V. Medir peças no sistema métrico com micrômetro. I. Demonstrar atenção a detalhes. I. Organizar o ambiente de trabalho e as atividades.', knowledge: '6. Micrômetros (6.5)', strategy: 'Exercício prático supervisionado de medição com micrômetros e preenchimento de relatório, comparando com medidas do paquímetro.', resources: 'Laboratório de Metrologia, micrômetros, paquímetros, peças, relatório.' },
  { id: 'c10', date: '07/04/2026', hours: 2, capacities: 'VI. Verificar dimensões e perfis com verificadores.', knowledge: '7. Verificadores (7.1, 7.2)', strategy: 'Demonstração do uso de calibradores de folga, raio e rosca. Exercício prático de verificação em peças.', resources: 'Laboratório de Metrologia, jogos de verificadores, pecas com roscas e raios.' },
  { id: 'c11', date: '14/04/2026', hours: 2, capacities: 'VII. Medir por comparação com relógio apalpador e comparador.', knowledge: '8. Relógios comparadores e apalpadores (8.1, 8.2)', strategy: 'Exposição sobre os tipos e características dos relógios. Demonstração de montagem em suportes magnéticos.', resources: 'Laboratório de Metrologia, relógios comparadores e apalpadores, suportes.' },
  { id: 'c12', date: '28/04/2026', hours: 2, capacities: 'VII. Medir por comparação com relógio apalpador e comparador.', knowledge: '8. Relógios comparadores e apalpadores (8.3, 8.4)', strategy: 'Exercício prático de zeragem com blocos-padrão e medição por comparação (ex: planicidade, concentricidade).', resources: 'Laboratório de Metrologia, relógios, suportes, blocos-padrão, desempeno.' },
  { id: 'c13', date: '05/05/2026', hours: 2, capacities: 'VIII. Medir peças com goniômetro.', knowledge: '9. Goniômetro (9.1 a 9.4)', strategy: 'Demonstração do uso do goniômetro (transferidor de grau) para medição de ângulos em peças.', resources: 'Laboratório de Metrologia, goniômetros, peças com chanfros e ângulos.' },
  { id: 'c14', date: '12/05/2026', hours: 2, capacities: 'Todas as capacidades técnicas e socioemocionais da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: 'Revisão geral de todos os instrumentos. Planejamento em grupo para a execução do desafio da SA.', resources: 'Sala de aula, projetor, material da SA, desenhos técnicos.' },
  { id: 'c15', date: '19/05/2026', hours: 2, capacities: 'Todas as capacidades técnicas e socioemocionais da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: 'Início da Execução do Desafio: Análise do desenho técnico e início das medições do lote de "Pinos de Ancoragem".', resources: 'Laboratório de Metrologia, todos os instrumentos, lote de peças da SA, relatórios.' },
  { id: 'c20', date: '23/06/2026', hours: 2, capacities: 'Todas as capacidades técnicas e socioemocionais da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: 'Feedback final sobre o desempenho na SA. Autoavaliação e fechamento da Unidade Curricular.', resources: 'Sala de aula, instrumentos de avaliação preenchidos.' }
];

// --- CRONOGRAMA FUSI (TRANSCRIÇÃO LITERAL DOS PRINTS) ---
export const FUSI_SCHEDULE = [
  // FRESAGEM E AJUSTAGEM (Print 3)
  { id: 'f_fresa_1', date: '28/01 a 30/01/2026', hours: 12, capacities: '- Elaborar plano de trabalho... \n - Planejar ações \n - Demonstrar responsabilidade', knowledge: '1. Elementos de máquina \n 3. Processos de fabricação \n 5. Plano de trabalho \n 8. Segurança \n 7. Melo Ambiente', strategy: '- Exposição dialogada sobre a SA. \n - Análise em grupo dos desenhos técnicos. \n - Início da elaboração do plano de trabalho (folha de processo).', resources: '- Sala de aula \n - Projetor multimídia \n - Desenhos técnicos impressos \n - Modelos de plano de trabalho' },
  { id: 'f_fresa_2', date: '04/02 a 06/02/2026', hours: 12, capacities: '- Selecionar ferramentas... \n - Definir os parâmetros de usinagem... \n - Zelar pelo uso de equipamentos...', knowledge: '2. Ferramentas \n 8. Parâmetros de corte \n 9. Parâmetros de ferramenta \n 11. Fresagem (Tipos, Ferramentas, Acessórios)', strategy: '- Demonstração de ferramentas e acessórios da fresadora. \n - Exercícios práticos de cálculo de RPM e avanço. \n - Instrução sobre fixação de peças e ferramentas.', resources: '- Oficina de usinagem \n - Fresadora convencional \n - Ferramentas de corte e fixação \n - Calculadora, quadros' },
  { id: 'f_fresa_3', date: '11/02 a 05/03/2026', hours: 38, capacities: '- Realizar operações de baixa complexidade em fresadora... \n - Aplicar os procedimentos de refrigeração... \n - Controlar a qualidade...', knowledge: '11. Fresagem (Operações) \n 15. Controle da qualidade \n 16. Refrigeração', strategy: '- Prática supervisionada de usinagem (faceamento, rebaixos, superfícies paralelas e perpendiculares). \n - Autoinspeção dimensional durante o processo.', resources: '- Oficina de usinagem \n - Fresadora, morsas, calços \n - Paquímetro, esquadro \n - EPIs (óculos, protetor auricular)' },
  { id: 'f_fresa_4', date: '06/03 a 19/03/2026', hours: 20, capacities: '- Realizar operações de furação... \n - Realizar operações de rosqueamento... \n - Demonstrar visão sistêmica', knowledge: '12. Furação \n 13. Rosqueamento', strategy: '- Demonstração de furação na furadeira de coluna e fresadora. \n - Demonstração de rosqueamento manual com macho. \n - Prática supervisionada de furação e rosqueamento.', resources: '- Oficina de usinagem \n - Furadeira de coluna \n - Machos, desandador, óleo de corte \n - Brocas, escareadores' },
  { id: 'f_fresa_5', date: '20/03 a 28/03/2026', hours: 20, capacities: '- Controlar a qualidade... \n - Planejar ações \n - Demonstrar responsabilidade \n - Zelar pelo uso de equipamentos...', knowledge: '15. Controle da qualidade \n 5. Plano de trabalho (revisão)', strategy: '- Finalização e rebarbação de todas as peças. \n - Preenchimento do relatório de controle de qualidade. \n - Apresentação do conjunto de peças finalizadas. \n - Limpeza final das máquinas e organização da oficina.', resources: '- Oficina de usinagem \n - Bancada de ajustagem \n - Instrumentos de medição \n - Relatórios impressos' },
  
  // TORNEAMENTO (Prints 1 e 2)
  { id: 'f_torn_1', date: '13/03/2026', hours: 4, capacities: '- Definir os parâmetros de usinagem... \n - Demonstrar responsabilidade.', knowledge: '8. Parâmetros de corte \n 9. Parâmetros de ferramenta \n 10. Torneamento (Definição, Tipos) \n 16. Refrigeração (Definição)', strategy: 'Exposição dialogada e Estudo de caso: Apresentação da SA2 e do desafio da "AgroMaq". Discussão sobre segurança no torno. Introdução aos cálculos de parâmetros de corte.', resources: 'Sala de aula, projetor, quadro branco, calculadoras, tabelas de parâmetros de corte, desenhos técnicos das peças.' },
  { id: 'f_torn_2', date: '18/03/2026', hours: 4, capacities: '- Realizar operações de baixa complexidade em torno... \n - Organizar o ambiente de trabalho...', knowledge: '10.3. Ferramentas (Torneamento externo) \n 10.4. Acessórios (Placa, Contraponta) \n 10.8.1. Facear no torno \n 10.8.5. Fazer furo de centro no torno', strategy: 'Demonstração e Prática Supervisionada: Demonstração das operações de fixação da peça, faceamento e furação de centro. Prática inicial dos alunos.', resources: 'Oficina de usinagem, torno convencional, ferramentas de facear e broca de centro, material bruto, EPIs.' },
  { id: 'f_torn_3', date: '19/03 e 20/03/2026', hours: 8, capacities: '- Realizar operações de baixa complexidade em torno... \n - Controlar a qualidade das peças... \n - Aplicar os procedimentos de refrigeração...', knowledge: '10.8.2. Tornear superfície cilíndrica \n 10.8.4. Chanfrar no torno \n 15. Controle da qualidade \n 16.2. Fluidos de corte', strategy: 'Prática Supervisionada: Início da usinagem do "Eixo cilíndrico de quatro corpos". Foco no desbaste e torneamento dos diâmetros maiores, com medições constantes.', resources: 'Oficina de usinagem, torno, ferramentas de tornear, paquímetro, material bruto (aço 1020), fluido de corte, EPIs.' },
  { id: 'f_torn_4', date: '25/03 e 26/03/2026', hours: 8, capacities: '- Realizar operações de baixa complexidade em torno... \n - Controlar a qualidade das peças... \n - Zelar pelo uso de equipamentos...', knowledge: '10.8.2. Tornear superfície cilíndrica \n 10.8.12. Cortar no torno \n 15.2. Inspeção dimensional', strategy: 'Prática Supervisionada: Continuação e finalização do "Eixo cilíndrico de quatro corpos". Foco no acabamento, nos diâmetros menores e no corte no comprimento final.', resources: 'Oficina de usinagem, torno, ferramentas de tornear e bedame, paquímetro, micrômetro, EPIs.' },
  { id: 'f_torn_5', date: '27/03/2026', hours: 4, capacities: '- Definir os parâmetros de usinagem... \n - Realizar operações de rosqueamento... \n - Demonstrar visão sistêmica.', knowledge: '13. Rosqueamento (Definição, Ferramentas, Acessórios) \n 10.8.10. Roscar com cossinete no torno', strategy: 'Exposição dialogada e Demonstração: Apresentação do processo de rosqueamento com cossinete no torno e com macho na bancada. Início do planejamento para o "Eixo roscado" e "Manípulo".', resources: 'Sala de aula, oficina de usinagem, torno, cossinetes, porta-cossinetes, machos, desandadores.' },
  { id: 'f_torn_6', date: '01/04 e 02/04/2026', hours: 8, capacities: '- Realizar operações de baixa complexidade em torno... \n - Realizar operações de rosqueamento... \n - Demonstrar responsabilidade.', knowledge: '10.8.2. Tornear superfície cilíndrica \n 10.8.10. Roscar com cossinete no torno \n 15.1. Inspeção visual', strategy: 'Prática Supervisionada: Usinagem do "Eixo roscado". Torneamento do diâmetro externo e execução da rosca com cossinete, garantindo o acabamento e a funcionalidade.', resources: 'Oficina de usinagem, torno, ferramentas, cossinete, paquímetro, fluido de corte, EPIs.' },
  { id: 'f_torn_7', date: '03/04/2026', hours: 4, capacities: '- Realizar operações de furação... \n - Realizar operações de rosqueamento... \n - Organizar o ambiente de trabalho...', knowledge: '12. Furação (Definição, Tipos, Operações) \n 13.7.1. Roscar manualmente com macho na bancada', strategy: 'Demonstração e Prática Supervisionada: Usinagem do "Manípulo". Foco na furação em furadeira de bancada e na abertura de rosca manual com macho.', resources: 'Oficina de usinagem, furadeira de bancada, broca, morsa, machos, desandador, óleo de corte, EPIs.' },
  { id: 'f_torn_8', date: '08/04/2026', hours: 4, capacities: '- Controlar a qualidade das peças... \n - Demonstrar visão sistêmica. \n - Zelar pelo uso de equipamentos...', knowledge: '15. Controle da qualidade \n 1. Elementos de máquina (Montagem)', strategy: 'Trabalho em equipe e Simulação: Montagem do conjunto "Manípulo" e "Eixo roscado". Verificação da funcionalidade. Análise de falhas caso a montagem não ocorra. Preenchimento final das fichas.', resources: 'Oficina de usinagem, bancada, peças usinadas, instrumentos de medição, fichas de processo.' },
  { id: 'f_torn_9', date: '09/04/2026', hours: 4, capacities: '- Todas as capacidades da SA.', knowledge: 'Todos os conhecimentos da SA.', strategy: 'Revisão e Avaliação Final: Revisão geral dos processos. Avaliação final das peças produzidas e dos documentos gerados. Feedback Individual e em grupo sobre o desempenho na SA.', resources: 'Oficina de usinagem, sala de aula, todas as peças e documentos produzidos.' }
];

export const FULL_CAPACITIES_FUSI = [
  '### Torneamento, Fresagem, Ajustagem',
  '1. Definir os parâmetros de usinagem de torneamento convencional de acordo com as especificações técnicas.',
  '2. Realizar operações de baixa complexidade em torno convencional de acordo com as especificações, normas técnicas e de saúde e segurança no trabalho.',
  '3. Realizar operações de torneamento externo e interno conforme desenho técnico.',
  '4. Definir os parâmetros de usinagem de fresagem convencional de acordo com as especificações técnicas.',
  '5. Realizar operações de baixa complexidade em fresadora convencional de acordo com as especificações, normas técnicas e de saúde e segurança no trabalho.',
  '6. Realizar operações de fresagem de superfícies planas e esquadrejamento.',
  '7. Selecionar ferramentas aplicadas na montagem e desmontagem de elementos de máquina.',
  '8. Relacionar os processos de fabricação à sua aplicação na indústria.',
  '9. Relacionar os tipos de manutenção à sua aplicação na indústria.',
  '10. Elaborar plano de trabalho de acordo com normas e procedimentos de meio ambiente, de saúde e segurança no trabalho.',
  '11. Realizar operações de furação de acordo com as especificações, normas técnicas e de saúde e segurança no trabalho.',
  '12. Realizar operações de rosqueamento de acordo com as especificações, normas técnicas e de saúde e segurança no trabalho.',
  '13. Controlar a qualidade das peças usinadas, visualmente e por meio de instrumentos de acordo com as especificações técnicas.',
  '14. Aplicar os procedimentos de refrigeração nos processos de usinagem convencional.'
];

export const FULL_SOCIOEMOCIONAL_FUSI = [
  'Autogestão: 1. Planejar ações',
  'Autogestão: 2. Organizar o ambiente de trabalho e as atividades',
  'Autogestão: 3. Zelar pelo uso de equipamentos, instrumentos, ferramentas e materiais',
  'Autogestão: 4. Demonstrar responsabilidade',
  'Pensamento analítico: 5. Demonstrar visão sistêmica'
];

export const FULL_KNOWLEDGE_FUSI = [
  { topic: '1. Elementos de máquina', subtopics: ['1.1. Elementos de fixação: Porcas, Parafusos, Arruelas, Contra pino, Rebites, Pinos, Cavilhas', '1.2. Elementos de transmissão: Chavetas, Engrenagens, Polias, Correias, Acoplamentos, Roscas, Corrente, Eixos, Redutores, Variadores'] },
  { topic: '3. Processos de fabricação', subtopics: ['3.1. Definição', '3.3. Manufatura Subtrativa: Torneamento, Furação, Fresamento'] },
  { topic: '5. Plano de trabalho', subtopics: ['5.1. Definição', '5.2. Tipos', '5.3. Características'] },
  { topic: '8. Parâmetros de corte', subtopics: ['8.1. Cálculos: RPM, Vc, f, ap'] },
  { topic: '10. Torneamento', subtopics: ['10.1. Definição', '10.2. Tipos de tornos', '10.3. Ferramentas', '10.4. Acessórios', '10.5. Cálculos técnicos'] },
  { topic: '11. Fresagem', subtopics: ['11.1. Definição', '11.2. Tipos de fresadora', '11.3. Ferramentas', '11.4. Acessórios'] },
  { topic: '15. Controle da qualidade', subtopics: ['15.1. Inspeção visual', '15.2. Inspeção dimensional'] }
];

export const COMMON_SA_FUSI = [
  {
    id: 'sa-fusi-torneamento',
    title: 'Operação de Protótipos: Usinagem de Componentes para Transmissão Mecânica',
    context: 'A "AgroMaq Industrial", empresa especializada na fabricação de pequenos implementos agrícolas, enfrenta um problema crítico: a linha de produção de um de seus pulverizadores está parada devido à falta de um subconjunto de ajuste mecânico. O fornecedor original das peças (eixos, manípulos e luvas) encerrou suas atividades, e a compra de um novo lote de um fornecedor alternativo levaria semanas, causando prejuízos significativos. Para solucionar o problema de forma rápida e eficiente, a gerência decidiu internalizar a produção desses componentes. O departamento de engenharia disponibilizou os desenhos técnicos do conjunto e solicitou ao setor de usinagem a fabricação de um lote piloto para validação.\nVocês, como a equipe de operadores de máquinas da "AgroMaq", receberam a missão de produzir as primeiras unidades deste conjunto. A tarefa exige não apenas habilidade na operação das máquinas, mas também a capacidade de interpretar os desenhos, calcular os parâmetros de corte corretos, executar as operações de torneamento, furação e rosqueamento com precisão, e garantir a qualidade final para que as peças possam ser montadas e funcionem perfeitamente.',
    challenge: 'Com base nos desenhos técnicos fornecidos e no material bruto, a equipe deverá executar um projeto completo de usinagem, focando nas operações de torneamento, para fabricar os componentes:\na) Planejar e Calcular: Para cada peça a ser usinada (Eixo cilíndrico de quatro corpos, Eixo cilíndrico com canais, Eixo roscado, Manípulo, Eixo calibrado e Luva com dois corpos internos), a equipe deverá calcular e registrar os parâmetros de corte essenciais (Velocidade de Corte, RPM, avanço) para cada operação (facear, tornear, chanfrar, furar, roscar), considerando as ferramentas e o material especificados.\nb) Executar e Controlar: Utilizando o torno mecânico convencional e a furadeira de bancada, a equipe deverá usinar as peças seguindo a sequência operacional planejada. Durante todo o processo, será necessário aplicar corretamente o fluido de refrigeração, zelar pela organização e segurança do ambiente, e realizar o controle dimensional contínuo com paquímetro e micrômetro, preenchendo uma ficha de autoinspeção. As operações incluem:\n• No torno: faceamento, torneamento de múltiplos diâmetros, furação de centro, furação com broca helicoidal, corte de canais e rosqueamento com cossinete.\n• Na furadeira/bancada: furação e rosqueamento manual com macho para o "Manípulo".\nc) Montar e Validar: Ao final da usinagem, a equipe deverá realizar a montagem do "Manípulo" no "Eixo roscado" para comprovar a funcionalidade e a precisão do conjunto roscado, demonstrando uma visão sistêmica do processo produtivo.',
    expectedResults: [
      'Ao final desta Situação de Aprendizagem, a equipe de alunos deverá entregar:',
      'a) Peças Usinadas: Os componentes "Eixo cilíndrico de quatro corpos", "Eixo roscado" e "Manípulo" finalizados, limpos, sem rebarbas e em total conformidade com as dimensões, tolerâncias e acabamentos especificados nos desenhos técnicos.',
      'b) Ficha de Processo e Controle de Qualidade: Um documento para cada peça, preenchido com os parâmetros de corte calculados, a sequência de operações executadas e os valores medidos durante a autoinspeção dimensional.',
      'c) Conjunto Funcional Montado: A demonstração da montagem bem-sucedida do "Manípulo" no "Eixo roscado", evidenciando que as peças foram fabricadas corretamente e são intercambiáveis.'
    ]
  },
  {
    id: 'sa-fusi-fresagem',
    title: 'Projeto "Oficina Limpa": Planejamento e Construção de um Dispositivo Auxiliar de Usinagem',
    context: 'A "Fresanatec Soluções Industriais", uma empresa metalmecânica com 30 funcionários, especializada na fabricação de peças e na prestação de serviços de manutenção, acaba de investir na ampliação de seu parque de máquinas com a aquisição de uma nova fresadora convencional. O objetivo é aumentar a capacidade produtiva e diversificar os serviços oferecidos aos seus clientes. Para que a nova máquina atinja seu potencial máximo, o gerente de produção, Sr. Almeida, identificou a necessidade de fabricar um conjunto de acessórios e dispositivos de fixação que não acompanharam o equipamento. Esses componentes são importantes para a versatilidade, segurança e eficiência das futuras operações. O conjunto inclui: um bloco fresado para referência, um bloco com rebaixo para exercícios de posicionamento, castanhas moles para fixação de peças delicadas, uma base para as castanhas, mordentes de proteção em alumínio e um protótipo de coletor de serragem para manter a área limpa e segura.\nComo a equipe de usinadores experientes está totalmente alocada em projetos de clientes, o Sr. Almeida decidiu transformar essa necessidade interna em uma oportunidade de desenvolvimento para a nova equipe de aprendizes.\nVocês, como aprendizes de mecânica de usinagem, foram designados para este projeto. A tarefa consiste em assumir a responsabilidade por todo o processo de fabricação desses componentes, desde a análise dos desenhos técnicos até a entrega das peças prontas para uso.\nEste projeto é a sua chance de demonstrar iniciativa, planejamento e habilidade técnica, aplicando os fundamentos da usinagem em um cenário real e contribuindo diretamente para a melhoria da infraestrutura da empresa.',
    challenge: 'Como equipe de aprendizes da Fresanatec, vocês têm o desafio de planejar, executar e controlar a fabricação do conjunto completo de seis componentes para a nova fresadora convencional. O sucesso do projeto será medido não apenas pela qualidade final das peças, mas também pela sua capacidade de trabalhar de forma organizada, segura e sistêmica. Para isso, a equipe deverá:\na) Analisar criticamente os desenhos técnicos de cada uma das seis peças, interpretando todas as cotas, tolerâncias e especificações.\nb) Elaborar um plano de trabalho detalhado (folha de processo) para cada componente, definindo a sequência lógica das operações de usinagem (fresagem, furação, rosqueamento), selecionando as ferramentas de corte e de fixação adequadas, e calculando os parâmetros de corte (RPM, avanços) para cada operação.\nc) Aplicar as normas de saúde e segurança no trabalho, identificando os riscos envolvidos e utilizando corretamente os Equipamentos de Proteção Individual (EPIs) e Coletivos (EPCs).\nd) Executar as operações de fresagem de baixa complexidade (faceamento, rebaixos, superfícies paralelas e perpendiculares), furação e rosqueamento manual, seguindo o plano de trabalho estabelecido.\ne) Gerenciar o uso de fluidos de refrigeração durante a usinagem, aplicando-os de forma correta e seguindo os procedimentos para o descarte adequado dos resíduos (cavacos).\nf) Realizar o controle de qualidade dimensional e visual das peças ao longo do processo e na sua finalização, utilizando instrumentos de medição e garantindo que todas as especificações do projeto sejam atendidas.',
    expectedResults: [
      'Ao final desta Situação de Aprendizagem, espera-se que a equipe de aprendizes entregue:',
      'a) O conjunto de 6 (seis) componentes mecânicos (Bloco fresado, Bloco rebaixado, Castanha mole, Base para castanha, Mordente de proteção, Coletor de serragem) usinados, finalizados e em total conformidade com os respectivos desenhos técnicos, prontos para serem instalados e utilizados na fresadora.',
      'b) O Plano de Trabalho (Folha de Processo) completo e devidamente preenchido para cada um dos componentes fabricados, servindo como documentação técnica do processo executado.',
      'c) Um Relatório de Controle de Qualidade para cada peça, contendo as medições dimensionais críticas realizadas, comparadas com as especificadas no desenho, e a aprovação final do componente.',
      'd) O posto de trabalho limpo e organizado, com as ferramentas e instrumentos devidamente guardados e os resíduos (cavacos) segregados corretamente para o descarte.'
    ]
  }
];

export const FULL_RUBRICS_FUSI = [
  { capacity: 'Realizar operações de baixa complexidade em torno convencional.', nsa: 'Não consegue executar as operações básicas no torno de forma satisfatória ou segura, mesmo com apoio e demonstrações constantes.', apo: 'Tenta operar a máquina, mas demonstra insegurança e comete erros frequentes de posicionamento e avanço, necessitando de intervenção constante.', par: 'Opera o torno e executa as operações, mas precisa de orientação pontual do docente para corrigir a técnica, ajustar a máquina ou atingir a tolerância.', aut: 'Opera o torno com autonomia e segurança, executando todas as operações (facear, tornear, chanfrar, furar) com precisão dimensional e bom acabamento.' },
  { capacity: 'Controlar a qualidade das peças usinadas (Torneamento).', nsa: 'Não consegue realizar as medições de forma correta ou preencher a ficha de controle, mesmo com o apoio direto do docente.', apo: 'Tenta realizar as medições, mas demonstra dificuldade na leitura dos instrumentos e no preenchimento da ficha, exigindo acompanhamento constante.', par: 'Realiza o controle dimensional, mas necessita de auxílio pontual para manusear o micrômetro ou para interpretar alguma tolerância especificada.', aut: 'Realiza o controle dimensional com autonomia, utilizando corretamente paquímetro e micrômetro, e preenche a ficha de autoinspeção de forma completa e precisa.' },
  { capacity: 'Zelar pelo uso de equipamentos, instrumentos, ferramentas e materiais.', nsa: 'Danifica ferramentas ou instrumentos por mau uso ou não demonstra qualquer cuidado com os recursos da oficina, mesmo após repetidas orientações.', apo: 'Manuseia os equipamentos de forma descuidada, deixando ferramentas em locais inadequados ou não realizando a limpeza, necessitando de intervenção constante.', par: 'Manuseia os equipamentos de forma adequada na maior parte do tempo, mas requer lembretes pontuais sobre a limpeza ou guarda de algum item.', aut: 'Manuseia todos os equipamentos, ferramentas e instrumentos com o máximo cuidado, limpando-os e guardando-os corretamente por iniciativa própria.' },
  { capacity: 'Demonstrar visão sistêmica.', nsa: 'Não consegue compreender a relação entre as peças ou a importância da sua tarefa para o produto final, mesmo com o conjunto montado para análise.', apo: 'Foca apenas na execução da sua peça, demonstrando dificuldade em entender como ela irá interagir com as outras, necessitando de explicações constantes.', par: 'Compreende que as peças se montarão, mas precisa de questionamentos para relacionar a precisão dimensional com a funcionalidade do conjunto.', aut: 'Compreende e explica como a precisão de cada peça individual afeta a montagem e o funcionamento final do subconjunto, propondo melhorias no processo.' },
  { capacity: 'Elaborar plano de trabalho.', nsa: 'Não consegue preencher o plano de trabalho, mesmo com auxílio constante, ou deixa a maior parte em branco.', apo: 'Preenche o plano de trabalho com a ajuda constante do docente, cometendo erros na sequência de operações e no cálculo de parâmetros.', par: 'Elabora o plano de trabalho com autonomia, necessitando de pequenas correções na seleção de ferramentas ou no refinamento dos parâmetros.', aut: 'Elabora o plano de trabalho de forma completa e otimizada, propondo sequências eficientes e justificando a escolha dos parâmetros.' },
  { capacity: 'Definir as parâmetros de usinagem.', nsa: 'Não consegue realizar os cálculos de RPM or avanço, mesmo com fórmulas e auxílio. Insere valores aleatórios ou perigosos na máquina.', apo: 'Realiza os cálculos de parâmetros de corte com a supervisão constante do docente, cometendo erros que precisam ser corrigidos.', par: 'Calcula os parâmetros de corte de forma autônoma para materiais e operações comuns, utilizando tabelas e fórmulas, necessitando de pequenos ajustes.', aut: 'Define e otimiza os parâmetros de corte para diferentes materiais e ferramentas, justificando as escolhas para obter melhor acabamento e vida útil da ferramenta.' },
  { capacity: 'Realizar operações de baixa complexidade em fresadora.', nsa: 'Demonstra grande dificuldade em operar a máquina, apresentando riscos à sua segurança e à do equipamento, mesmo com supervisão direta.', apo: 'Realiza as operações com supervisão e intervenção constante do docente para corrigir a postura, a fixação da peça ou o manuseio dos comandos.', par: 'Opera a máquina de forma segura e executa as operações corretamente, solicitando auxílio pontual em situações específicas.', aut: 'Realiza todas as operações com autonomia, segurança e precisão, otimizando o processo para obter um bom acabamento.' },
  { capacity: 'Realizar operações de furação.', nsa: 'Demonstra grande dificuldade em operar a furadeira, com fixação inadequada da peça e uso incorreto da ferramenta, apresentando risco à segurança.', apo: 'Realiza operações de furação com supervisão constante, necessitando de auxílio para alinhar o furo, controlar o avanço ou aplicar fluido de corte.', par: 'Executa operações de furação de forma segura e autônoma, atingindo as especificações de diâmetro e posição na maioria das vezes, com auxílio pontual.', aut: 'Realiza operações de furação (passante, cega, escareado) com autonomia, precisão e segurança, selecionando corretamente brocas e parâmetros.' },
  { capacity: 'Realizar operações de rosqueamento.', nsa: 'Não consegue iniciar a rosca com o macho ou quebra a ferramenta com frequência, mesmo com supervisão.', apo: 'Realiza o rosqueamento manual com auxílio constante do docente para garantir o alinhamento e o movimento correto de avanço e retrocesso.', par: 'Executa o rosqueamento manual de forma autônoma, produzindo roscas funcionais, necessitando de orientação para evitar quebra de ferramenta.', aut: 'Realiza o rosqueamento manual com precisão, alinhamento e segurança, selecionando o macho e a broca corretos e aplicando a técnica adequada.' },
  { capacity: 'Aplicar os procedimentos de refrigeração.', nsa: 'Não aplica o fluido de corte ou o faz de forma perigosa/ineficaz, mesmo quando orientado.', apo: 'Aplica o fluido de corte apenas quando lembrado pelo docente, com dificuldade em direcionar o jato para a região de corte correta.', par: 'Aplica os procedimentos de refrigeração de forma autônoma e correta durante a usinagem, garantindo a lubrificação e o resfriamento adequados.', aut: 'Aplica e ajusta a refrigeração de forma otimizada, selecionando o tipo de fluido e vazão mais adequados para a operação e material.' },
  { capacity: 'Controlar a qualidade das peças usinadas (Fresagem/Ajustagem).', nsa: 'Não consegue manusear os instrumentos de medição ou realiza leituras incorretas, mesmo após orientação.', apo: 'Realiza as medições com dificuldade, necessitando de auxílio do docente para posicionar o instrumento e interpretar os resultados.', par: 'Utiliza os instrumentos de medição de forma correta e autônoma, realizando o controle dimensional e visual das peças conforme solicitado.', aut: 'Realiza o controle de qualidade com precisão e adota medidas preventivas para garantir a conformidade dos lotes.' }
];

export const SAMPLE_PLANS: TeachingPlan[] = [
  {
    id: 'plan-usinagem-beretella',
    profileId: 'beretella',
    courseName: 'SMO - Mecânico de Usinagem Convencional',
    modality: 'Presencial',
    totalHours: 400,
    objective: 'Desenvolver capacidades técnicas e socioemocionais relativas aos elementos de máquina, ferramentas, processos de fabricação, manutenção e usinagem convencional seguindo normas de saúde e segurança.',
    methodology: 'Metodologia SENAI de Educação Profissional (MSEP). Uso de situações de aprendizagem realistas através do Cronograma Integradror.',
    evaluation: 'Contínua baseada em rubricas de desempenho e qualidade das peças usinadas.',
    bibliography: 'Guia de Aprendizagem Profissional SENAI: Fresamento e Torneamento. NBR 10067, NBR 8403, VIM.',
    createdAt: new Date().toISOString(),
    units: [
      {
        id: 'uc-lidt-beretella',
        name: 'LEITURA E INTERPRETAÇÃO DE DESENHO TÉCNICO',
        calendar: { startDate: '2026-01-26', endDate: '2026-06-15', markings: [] },
        basicCapacities: ['Interpretar desenhos técnicos', 'Elaborar croquis', 'Interpretar tolerâncias'],
        socioemocionalCapacities: ['Atenção a detalhes', 'Senso crítico'],
        knowledge: [{ topic: '1. Desenho técnico', subtopics: ['1.1 Normas', '1.4 Linhas', '1.5 Escalas'] }],
        learningSituations: [],
        rubrics: [],
        schedule: LIDT_SCHEDULE
      },
      {
        id: 'uc-crd-beretella',
        name: 'CONTROLE DIMENSIONAL',
        calendar: { startDate: '2026-01-26', endDate: '2026-06-23', markings: [] },
        basicCapacities: ['Medir com paquímetro', 'Medir com micrômetro'],
        socioemocionalCapacities: ['Organização'],
        knowledge: [{ topic: '1. Metrologia', subtopics: ['VIM', 'Erros'] }],
        learningSituations: [],
        rubrics: [],
        schedule: CRD_SCHEDULE
      },
      {
        id: 'uc-fusi-beretella',
        name: 'FUNDAMENTOS DA USINAGEM',
        calendar: { startDate: '2026-01-28', endDate: '2026-06-24', markings: [] },
        basicCapacities: FULL_CAPACITIES_FUSI,
        socioemocionalCapacities: FULL_SOCIOEMOCIONAL_FUSI,
        knowledge: FULL_KNOWLEDGE_FUSI,
        learningSituations: COMMON_SA_FUSI,
        rubrics: FULL_RUBRICS_FUSI,
        schedule: FUSI_SCHEDULE
      }
    ]
  }
];
